### ISSUE TITLE
Not able to execute 

### ISSUE THREAD

**Issue by cpatel22** [mrholek/CoreUI-React#50] opened 2018-01-31 15:30 UTC
Not able to execute

**Comment by xidedix** [comment] 2018-01-31 15:52
Hi @cpatel22 
Could you provide steps to reproduce?

**Comment by cpatel22** [comment] 2018-01-31 16:07
http://coreui.io/docs/getting-started/react-js-version/

I follow the step in this url.

**Comment by cpatel22** [comment] 2018-01-31 16:10
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\cpatel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @coreui/react@1.0.9~prestart: @coreui/react@1.0.9
6 info lifecycle @coreui/react@1.0.9~start: @coreui/react@1.0.9
7 verbose lifecycle @coreui/react@1.0.9~start: unsafe-perm in lifecycle true
8 verbose lifecycle @coreui/react@1.0.9~start: PATH: C:\Users\cpatel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\ETrackingSystem\React_Full_Project\node_modules\.bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Users\cpatel\AppData\Local\Microsoft\WindowsApps;C:\Users\username\AppData\Roaming\npm;;c:\Users\cpatel\AppData\Roaming\npm\;C:\Users\cpatel\AppData\Local\Programs\EmEditor;C:\Program Files\Microsoft VS Code\bin;C:\Users\cpatel\AppData\Roaming\npm;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle @coreui/react@1.0.9~start: CWD: D:\ETrackingSystem\React_Full_Project
10 silly lifecycle @coreui/react@1.0.9~start: Args: [ '/d /s /c',
10 silly lifecycle   'webpack-dev-server --progress --color --inline --env.dev' ]
11 silly lifecycle @coreui/react@1.0.9~start: Returned: code: 1  signal: null
12 info lifecycle @coreui/react@1.0.9~start: Failed to exec start script
13 verbose stack Error: @coreui/react@1.0.9 start: `webpack-dev-server --progress --color --inline --env.dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\cpatel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\cpatel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @coreui/react@1.0.9
15 verbose cwd D:\ETrackingSystem\React_Full_Project
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cpatel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @coreui/react@1.0.9 start: `webpack-dev-server --progress --color --inline --env.dev`
22 error Exit status 1
23 error Failed at the @coreui/react@1.0.9 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by cpatel22** [comment] 2018-01-31 16:10
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @coreui/react@1.0.9 start: `webpack-dev-server --progress --color --inline --env.dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @coreui/react@1.0.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cpatel\AppData\Roaming\npm-cache\_logs\2018-01-31T16_09_43_864Z-debug.log

**Comment by xidedix** [comment] 2018-01-31 16:22
assuming you've got node and npm installed 
````bash
cd React_Full_Project
npm install
npm start
````

**Comment by cpatel22** [comment] 2018-01-31 16:37
Thanks,

**Comment by xidedix** [comment] 2018-01-31 17:35
I'm closing this since it appears to be answered above. Please comment and it will be reopened if you feel the issue has not been resolved.

**Closed by xidedix** 2018-01-31 17:35 UTC
