### ISSUE TITLE
build error on first run

### ISSUE THREAD

**Issue by rmzdempsey** [mrholek/CoreUI-React#21] opened 2017-10-18 12:48 UTC
I cannot get past this error on first execution....

ERROR in ./src/components/Breadcrumb/Breadcrumb.js
Module build failed: SyntaxError: Unexpected token (21:26)

I have copied the React_Starter dir to ~/coreiu, cd into it, run npm install, then npm start
then above error results.

**Comment by uanjoze** [comment] 2017-10-26 09:25
Probably because of lack of support for the spread operator `...`

You can install the Babel preset and activate it in your **webpack.config.js**

To install the preset:
`npm install --save-dev babel-preset-stage-2`

In your **webpack.config.js**, where it now says:
`presets: ['react', 'env']`
replace with:
`presets: ['react', 'env', 'stage-2']

**Comment by iviarki** [comment] 2017-11-15 14:15
I experienced this error too when I copied from the cloned repo's location. Turns out, I did not specify to copy hidden files, so [.babelrc](https://github.com/mrholek/CoreUI-React/blob/master/React_Starter/.babelrc) was left behind. 

If you run npm install && npm start from where you cloned the repo to, did it work?

**Comment by rmzdempsey** [comment] 2017-11-15 14:18
I deleted the downloaded node modules directory  then ran npm install and
it worked no problems at all.

**Comment by xidedix** [comment] 2017-12-22 12:01
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be reopened if you feel the issue has not been resolved / the question has not been answered

**Closed by xidedix** 2017-12-22 12:01 UTC
