### ISSUE TITLE
How to add class 'active' to Label?

### ISSUE THREAD

**Issue by loudking** [mrholek/CoreUI-React#33] opened 2017-12-02 09:11 UTC
Hi can you please provide an example on how to add class 'active' to a label when a corresponding radio button is clicked? Below code is taken from CoreUI-React-master/React_Full_Project/src/views/Dashboard.js. Maybe you can show how to show how to set label option1 is active when Day is clicked?

```
                    <ButtonToolbar className="float-right" aria-label="Toolbar with button groups">
                      <ButtonGroup className="mr-3" data-toggle="buttons" aria-label="First group">
                        <Label htmlFor="option1" className="btn btn-outline-secondary">
                          <Input type="radio" name="options" id="option1"/> Day
                        </Label>
                        <Label htmlFor="option2" className="btn btn-outline-secondary active">
                          <Input type="radio" name="options" id="option2" defaultChecked/> Month
                        </Label>
                        <Label htmlFor="option3" className="btn btn-outline-secondary">
                          <Input type="radio" name="options" id="option3"/> Year
                        </Label>
                      </ButtonGroup>
                    </ButtonToolbar>
```

**Comment by xidedix** [comment] 2017-12-04 13:18
Hi @loudking 
Let's rewrite this part to make it more consistent with `reactstrap` components, and to handle `onClick` event like this:
````html
<ButtonToolbar className="float-right" aria-label="Toolbar with button groups">
  <ButtonGroup className="mr-3" aria-label="First group">
    <Button color="outline-secondary" onClick={() => this.onRadioBtnClick(1)} active={this.state.radioSelected=== 1}>Day</Button>
    <Button color="outline-secondary" onClick={() => this.onRadioBtnClick(2)} active={this.state.radioSelected=== 2}>Month</Button>
    <Button color="outline-secondary" onClick={() => this.onRadioBtnClick(3)} active={this.state.radioSelected=== 3}>Year</Button>
  </ButtonGroup>
</ButtonToolbar>
````
add method to handle radio button click:
````javascript
onRadioBtnClick(radioSelected) {
  // alert(`onRadioBtnClick ${radioSelected}`);
  this.setState({
    radioSelected: radioSelected
  });
}
````

and modify constructor to assign the initial state of `radioSelected` and bind method `onRadioBtnClick `
````javascript
constructor(props) {
  super(props);

  this.toggle = this.toggle.bind(this);
  this.onRadioBtnClick = this.onRadioBtnClick.bind(this);

  this.state = {
    dropdownOpen: false,
    radioSelected: 2
  };
````

hope this helps

**Comment by xidedix** [comment] 2017-12-22 12:00
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be reopened if you feel the issue has not been resolved / the question has not been answered.

**Closed by xidedix** 2017-12-22 12:00 UTC
